name: IPTV-Auto-Sync

on:
  schedule:
    - cron: '0 */8 * * *'  # 每8小时自动运行一次
  workflow_dispatch:       # 支持手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests pycryptodome

      - name: Execute Script
        run: python update_all.py

      - name: Deploy to Repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add live.m3u
          git commit -m "Auto Update $(date)" || exit 0
          git push
