name: Auto Gather Nodes
on:
  schedule:
    - cron: '0 */4 * * *' # 每 4 小时全自动运行一次
  workflow_dispatch:      # 支持手动一键运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run
        run: |
          pip install requests
          python gather.py
      - name: Commit
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "NodeBot"
          git add nodes.txt
          git commit -m "Update nodes" || exit 0
          git push
