name: IPTV-Full-挖掘机

on:
  schedule:
    - cron: '0 22,4,12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: 安装依赖
        run: pip install requests pycryptodome # 关键加密库
      - name: 执行联动抓取
        run: python update_all.py
      - name: 同步至仓库
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -f "live.txt" ]; then
            git add live.txt
            git commit -m "联动抓取全套源 $(date)" || exit 0
            git push
          fi
