name: IPTV-Auto-Sync

on:
  schedule:
    - cron: '0 22,4,12 * * *' # 北京时间早、中、晚自动更新
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests pycryptodome # 必须安装此依赖

      - name: Execute Script
        run: python update_all.py

      - name: Deploy to Repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # 修正点：只 add live.txt，解决 1000069027.jpg 中的报错
          if [ -f "live.txt" ]; then
            git add live.txt
            git commit -m "Auto Update $(date)" || exit 0
            git push
          fi
